### ISSUE TITLE
Invalid header value

### ISSUE THREAD

**Issue by Dutisto** [ts1829/readwise_exporter#1]
Hello !
Thanks for this nice tool !
I tried to use it, however I got the error 

`  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1285, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.7/http/client.py", line 1222, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b'Token [HERE IS MY TOKEN]\n'`

Do you have any idea why ?

**Comment by ts1829** [comment]
You have a newline character `\n` following your token shown in your error message `ValueError: Invalid header value b'Token [HERE IS MY TOKEN]\n'`
Remove the blank line after your token from your `token.txt` file.

**Comment by Dutisto** [comment]
Oh... Got to used xxd to remove it... Sorry for disturbing !
